id: P98A58F6F
initial_creation_type: input
source_metadata:
  title: Vigrahavyāvartanīkārikā
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Buddhist
  data entry: Richard Mahoney
  contribution to GRETIL: Richard Mahoney
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:19:54.187587'
last_modified_at: '2022-03-09T15:19:54.187600'
